modules/webform/src/Form/WebformResultsClearForm.php
<?php

namespace Drupal\webform\Form;

use Drupal\Core\Form\FormStateInterface;

/**
 * Webform for webform results clear webform.
 */
class WebformResultsClearForm extends WebformSubmissionsDeleteFormBase {

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'webform_results_clear';
  }

  /**
   * {@inheritdoc}
   */
  public function getQuestion() {
    $t_args = ['%label' => $this->getLabel()];
    return $this->t('Clear all %label submissions?', $t_args);
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    $submission_total = $this->submissionStorage->getTotal($this->webform, $this->sourceEntity);
    if ($submission_total) {
      return parent::buildForm($form, $form_state);
    }
    else {
      $t_args = ['%label' => $this->getLabel()];
      $form['message'] = [
        '#type' => 'webform_message',
        '#message_type' => 'error',
        '#message_message' => $this->t('There are no %label submissions.', $t_args),
      ];
      return $form;
    }
  }

  /**
   * {@inheritdoc}
   */
  public function getWarning() {
    $t_args = ['%label' => $this->getLabel()];
    return [
      '#type' => 'webform_message',
      '#message_type' => 'warning',
      '#message_message' => $this->t('Are you sure you want to clear all %label submissions?', $t_args) . '<br/>' .
        '<strong>' . $this->t('This action cannot be undone.') . '</strong>',
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function getDescription() {
    $submission_total = $this->submissionStorage->getTotal($this->webform, $this->sourceEntity);

    $t_args = [
      '%label' => $this->getLabel(),
      '@total' => $submission_total,
      '@submissions' => $this->formatPlural($submission_total, 'submission', 'submissions'),
    ];

    return [
      'title' => [
        '#markup' => $this->t('This action will…'),
      ],
      'list' => [
        '#theme' => 'item_list',
        '#items' => [
          $this->t('Remove @total %label @submissions', $t_args),
          ['#markup' => '<em>' . $this->t('Take a few minutes to complete') . '</em>'],
        ],
      ],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function getConfirmInput() {
    $t_args = ['%label' => $this->getLabel()];
    return [
      '#type' => 'checkbox',
      '#title' => $this->t('Yes, I want to clear all %label submissions', $t_args),
      '#required' => TRUE,
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function getCancelUrl() {
    return $this->requestHandler->getUrl($this->webform, $this->sourceEntity, 'webform.results_submissions');
  }

  /**
   * {@inheritdoc}
   */
  public function getMessage() {
    $t_args = ['%label' => $this->getLabel()];
    $this->t('Webform %label submissions cleared.', $t_args);
  }

}

modules/webform/templates/webform-codemirror.html.twig
{#
/**
 * @file
 * Theme implementation for 'CodeMirror' code.
 *
 * Available variables
 * - code: The code.
 * - type: The type of code.
 * - mode: The CodeMirror mode used to format the code.
 *
 * @see http://codemirror.net/doc/manual.html#option_mode
 * @see \Drupal\webform\Element\WebformCodeMirror()
 * @see template_preprocess_webform_codemirror()
 *
 * @ingroup themeable
 */
#}
{% if type == 'html' %}
  {{ attach_library('webform/webform.element.codemirror.html') }}
{% elseif type == 'yaml' %}
  {{ attach_library('webform/webform.element.codemirror.yaml') }}
{% else %}
  {{ attach_library('webform/webform.element.codemirror.text') }}
{% endif %}
<pre class="js-webform-codemirror-runmode webform-codemirror-runmode" data-webform-codemirror-mode="{{ mode }}">{{ code }}</pre>

modules/webform/templates/webform-composite-address.html.twig
{#
/**
 * @file
 * Default theme implementation of an address composite webform element.
 *
 * Available variables:
 * - content: The address webform element to be output.
 * - flexbox: Determines if Flexbox layout should be applied to the composite
 *   element.
 *
 * @see template_preprocess_webform_composite_address()
 *
 * @ingroup themeable
 */
#}
{% if flexbox %}

  {% if content.address %}
    <div class="webform-flexbox">
      <div class="webform-flex webform-flex--1"><div class="webform-flex--container">{{ content.address }}</div></div>
    </div>
  {% endif %}

  {% if content.address_2 %}
    <div class="webform-flexbox">
      <div class="webform-flex webform-flex--1"><div class="webform-flex--container">{{ content.address_2 }}</div></div>
    </div>
  {% endif %}

  <div class="webform-flexbox">
    {% if content.city %}
      <div class="webform-flex webform-flex--1"><div class="webform-flex--container">{{ content.city }}</div></div>
    {% endif %}
    {% if content.state_province %}
      <div class="webform-flex webform-flex--1"><div class="webform-flex--container">{{ content.state_province }}</div></div>
    {% endif %}
    {% if content.postal_code %}
      <div class="webform-flex webform-flex--1"><div class="webform-flex--container">{{ content.postal_code }}</div></div>
    {% endif %}
  </div>

  {% if content.country %}
    <div class="webform-flexbox">
      <div class="webform-flex webform-flex--1"><div class="webform-flex--container">{{ content.country }}</div></div>
    </div>
  {% endif %}

{% else %}
  {{ content }}
{% endif %}

modules/webform/templates/webform-composite-link.html.twig
{#
/**
 * @file
 * Default theme implementation of a link composite webform element.
 *
 * Available variables:
 * - content: The link webform element to be output.

 * @see template_preprocess_webform_composite_link()
 *
 * @ingroup themeable
 */
#}
{{ content }}

modules/webform/templates/webform-composite-telephone.html.twig
{#
/**
 * @file
 * Default theme implementation of a telephone composite webform element.
 *
 * Available variables:
 * - content: The telephone webform element to be output.
 * - flexbox: Determines if Flexbox layout should be applied to the composite
 *   element.
 *
 * @see template_preprocess_webform_composite_telephone()
 *
 * @ingroup themeable
 */
#}
{{ content.type }}
{{ content.phone }}
{{ content.ext }}

modules/webform/templates/webform-container-base-text.html.twig
{#
/**
 * @file
 * Default theme implementation for a webform base container as text.
 *
 * Available variables:
 * - element: The form element.
 * - title: The label for the container.
 * - value: The content for the container.
 * - options Associative array of options for element.
 *   - email: Flag to determine if element is for an email.
 */
#}
{{ value }}

modules/webform/templates/webform-contribute.html.twig
{#
/**
 * @file
 * Default theme implementation for the webform contribute community info.
 *
 * Available variables:
 * - account: The user or organization account profile.
 * - membership: The user or organizations membership status.
 * - contribution: The user or organizations contributions.
 */
#}
{{ attach_library('webform/webform.contribute') }}

<div class="webform-contribute-community-info">
  <h2 class="webform-contribute-community-info__header">{{ 'Community Information'|t }}</h2>
  <div class="webform-contribute-community-info__items">
    <div class="webform-contribute-community-info__item">
      <span class="webform-contribute-community-info__item-icon webform-contribute-community-info__item-icon--account" id="contribute-info-account"></span>
      <div class="webform-contribute-community-info__item-details">
        <h3 class="webform-contribute-community-info__item-title">{{ 'Drupal.org Account'|t }}</h3>
        {{ account.value }}
        {% if account.description %}
          <br/>{{ account.description }}
        {% endif %}
      </div>
    </div>
    <div class="webform-contribute-community-info__item">
      <span class="webform-contribute-community-info__item-icon webform-contribute-community-info__item-icon--membership" id="contribute-info-membership"></span>
      <div class="webform-contribute-community-info__item-details">
        <h3 class="webform-contribute-community-info__item-title">{{ 'Drupal Association Membership'|t }}</h3>
        {{ membership.value }}
        {% if membership.description %}
          <br/>{{ membership.description }}
        {% endif %}
      </div>
    </div>
    <div class="webform-contribute-community-info__item">
      <span class="webform-contribute-community-info__item-icon webform-contribute-community-info__item-icon--contribution" id="contribute-info-contribution"></span>
      <div class="webform-contribute-community-info__item-details">
        <h3 class="webform-contribute-community-info__item-title">{{ 'Contributions to Drupal'|t }}</h3>
        {{ contribution.value }}
        {% if contribution.description %}
          <br/>{{ contribution.description }}
        {% endif %}
      </div>
    </div>
  </div>
</div>

modules/webform/templates/webform-element-audio-file.html.twig
{#
/**
 * @file
 * Default theme implementation for an audio file element.
 *
 * Available variables:
 * - element: The element.
 * - value: The element's value.
 * - options Associative array of options for element.
 * - file: The element's File object.
 * - file_link: Link to the file.
 *
 * @see http://caniuse.com/#feat=audio
 * @see http://www.w3schools.com/html/html5_audio.asp
 */
#}
{% if extension == 'mp3' %}
  <div class="webform-audio-file">
    <audio controls>
      <source src="{{ uri }}" type="{{ type }}">
    </audio>
  </div>
{% endif %}
<div>{{ file_link }}</div>

modules/webform/templates/webform-element-base-html.html.twig
{#
/**
 * @file
 * Default theme implementation for a webform base element as html.
 *
 * Available variables:
 * - element: The element.
 * - title: The label for the element.
 * - value: The content for the element.
 * - item: The form item used to display the element.
 * - options Associative array of options for element.
 *   - multiline: Flag to determine if value spans multiple lines.
 *   - email: Flag to determine if element is for an email.
 */
#}
{% if options.email %}
  {% if title %}<b>{{ title }}</b><br />{% endif %}{{ value }}<br /><br />
{% else %}
  {{ item }}
{% endif %}

modules/webform/templates/webform-element-help.html.twig
{#
/**
 * @file
 * Theme implementation for webform element help
 *
 * Available variables
 * - element: form element
 * - help: Help content.
 * - help_icon: Help icon.
 *
 * @see template_preprocess_webform_element_help()
 *
 * @ingroup themeable
 */
#}
{% spaceless %}
{{ attach_library('webform/webform.element.help') }}
<span{{ attributes }}><span aria-hidden="true">?</span></span>
{% endspaceless %}

modules/webform/templates/webform-handler-remote-post-summary.html.twig
{#
/**
 * @file
 * Default theme implementation for a summary of a webform remote posts handler.
 *
 * Available variables:
 * - settings: The current configuration for this remote post handler.
 * - handler: The remote post handler.
 *
 * @ingroup themeable
 */
#}
{% if settings.debug %}<b class="color-error">{{ 'Debugging is enabled'|t }}</b><br />{% endif %}
<b>{{ 'Completed URL:'|t }}</b> {{ settings.completed_url }}<br />
{% if settings.updated_url %}<b>{{ 'Updated URL:'|t }}</b> {{ settings.updated_url }}<br />{% endif %}
{% if settings.deleted_url %}<b>{{ 'Deleted URL:'|t }}</b> {{ settings.deleted_url }}<br />{% endif %}
{% if settings.draft_url %}<b>{{ 'Draft URL:'|t }}</b> {{ settings.draft_url }}<br />{% endif %}
{% if settings.converted_url %}<b>{{ 'Converted URL:'|t }}</b> {{ settings.converted_url }}<br />{% endif %}
<b>{{ 'Method:'|t }}</b> {{ settings.method }}<br />
{% if settings.method == 'POST' %}<b>{{ 'Type:'|t }}</b> {{ settings.type }}<br />{% endif %}
{% if settings.message or settings.messages %}<b>{{ 'Response message:'|t }}</b> {{ 'Yes'|t }}<br/>{% endif %}

modules/webform/templates/webform-message.html.twig
{#
/**
 * @file
 * Default theme implementation of a Webform message container.
 *
 * Available variables:
 * - attributes: HTML attributes for the containing element.
 * - message: The rendered status_messages elements.
 * - has_parent: A flag to indicate that the container has one or more parent
 *    containers.
 * - closed: A flag to indicate that the message has been been closed and should
 *    not be displayed.
 *
 * @see template_preprocess_webform_message()
 *
 * @ingroup themeable
 */
#}
{%
  set classes = [
    has_parent ? 'js-form-wrapper',
    has_parent ? 'form-wrapper',
  ]
%}
{% if not closed %}
<div{{ attributes.addClass(classes) }}>{{ message }}</div>
{% endif %}

modules/webform/templates/webform-progress-tracker.html.twig
{#
/**
 * @file
 * Default theme implementation for webform wizard progress tracker.
 *
 * Available variables:
 * - webform: A webform.
 * - pages: Associatve array of wizard pages.
 * - progress: Array of wizard progress containing page titles.
 * - current_page: Current wizard page key.
 * - current_index: The current wizard page index.
 * - max_pages: Maximum number of pages that progress text should be displayed on.
 *
 * @see template_preprocess_webform_progress_bar()
 * @see https://www.w3.org/WAI/tutorials/forms/multi-page/
 *
 * @ingroup themeable
 */
#}
{{ attach_library('webform/webform.progress.tracker') }}

<ul class="webform-progress-tracker progress-tracker progress-tracker--center">
  {% for index, page in progress %}
    {% set is_completed = index < current_index %}
    {% set is_active = index == current_index %}
    {%
      set classes = [
        'progress-step',
        is_completed ? 'is-complete',
        is_active ? 'is-active',
      ]
    %}
    <li{{ attributes.setAttribute('data-webform-page', page.name).setAttribute('title', page.title).setAttribute('class', '').addClass(classes) }}>
      <span class="progress-marker">{{ index + 1 }}</span>
      {% if progress|length < max_pages %}
        <span class="progress-text">
          <div class="progress-title">
            {% if is_active or is_completed %}
              <span class="visually-hidden">{{ is_active ? 'Current'|t : 'Completed'|t }}: </span>
            {% endif %}
            {{ page.title }}
          </div>
        </span>
      {% endif %}
    </li>
  {% endfor %}
</ul>

modules/webform/templates/webform-submission-form.html.twig
{#
/**
 * @file
 * Default theme implementation for a webform submission form.
 *
 * Available variables:
 * - form: The webform submission form.
 *
 * @ingroup themeable
 */
#}
{{ form }}

modules/webform/templates/webform-submission-navigation.html.twig
{#
/**
 * @file
 * Default theme implementation to navigate webform submission.
 *
 * Available variables:
 * - prev_url: URL to the previous webform submission.
 * - next_url: URL to the next webform submission.
 * - webform_id: The webform ID. Provided for context.
 * - webform_title: The webform title. Provided for context.
 *
 * @see template_preprocess_webform_submission_navigation()
 *
 * @ingroup themeable
 */
#}
{% if prev_url or next_url %}
  <nav id="webform-submission-navigation-{{ webform_id }}" class="webform-submission-navigation" role="navigation" aria-labelledby="webform-submission-label-{{ webform_id }}">
    <h2 class="visually-hidden" id="webform-submission-label-{{ webform_id }}">Submission navigation links for {{ webform_title }}</h2>
    <ul class="webform-submission-pager">
      {% if prev_url %}
        <li class="webform-submission-pager__item webform-submission-pager__item--previous">
          <a href="{{ prev_url }}" rel="prev" title="{{ 'Go to previous page'|t }}"><b>{{ '‹'|t }}</b> {{ 'Previous submission'|t }}</a>
        </li>
      {% endif %}
      {% if next_url %}
        <li class="webform-submission-pager__item webform-submission-pager__item--next">
          <a href="{{ next_url }}" rel="next" title="{{ 'Go to next page'|t }}">{{ 'Next submission'|t }} <b>{{ '›'|t }}</b></a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}